services:
    db:
        image: postgres:15
        networks:
            - intra
        env_file:
            - .env
        volumes:
            - pgdata:/var/lib/postgresql/data

    backend:
        build: ./backend
        ports:
            - "8000:8000"
            - "53200-53300:53200-53300"
        networks:
            - intra
        depends_on:
            - db
            - redis
        env_file:
            - .env
        volumes:
            - ./backend:/app/backend
    
    redis:
        image: redis:7
        networks:
            - intra

networks:
    intra:
        external: true

volumes:
    pgdata:
